#!/bin/bash

## Print out the environment this terminal is working in for java 
##
## @author Spencer Imbleau
## @version July 2019

# Print usage for the program
print_usage() {
	echo "Usage: \"jenv\""
	return 1
}

# Check if the bin (classpath) directory exists
# 
# @params $1 - the path of a bin/classpath folder
# @returns 0 if the classpath directory exists conventionally
# @returns 1 if $CLASSPATH is null
# @returns 2 if $CLASSPATH is not a directory
# @returns 3 if $CLASSPATH is not named bin
check_bin_path() {
	# Check if CLASSPATH is empty
	if [ -z "$1" ]
	then
		return 1
	fi
	# Check if CLASSPATH is a directory
	if [ ! -d "$1" ]
	then
		return 2
	fi
	# Check if CLASSPATH is named 'bin' conventionally
	if [ "${1: -4}" != "/bin" ]
	then
		return 3
	fi
	return 0
}

# Check if a directory exists
# 
# @params $1 - the path of a folder
# @returns 0 if the folder exists, 1 otherwise
check_dir_path() {
	# Check if source path is a directory
	if [ ! -d "$1" ]
	then
		return 1
	fi
	return 0
}

# Entry point of the program
# 
# @params $@ - the command line arguments
# @returns 0 if the program executed successfully, 1 otherwise
main() {
	# Check 0 args was passed
	if [ $# -ne 0 ]
	then
		print_usage
		return 1
	fi

	# Program can start! Proper usage.
	# --------------------------------

	# Index important locations
	STRUCTURE_PATH=$(realpath "$CLASSPATH/.." 2> /dev/null)
	BIN_PATH=$(realpath "$CLASSPATH" 2> /dev/null)
	SOURCE_PATH=$(realpath "$CLASSPATH/../src" 2> /dev/null)
	LIB_PATH=$(realpath "$CLASSPATH/../lib" 2> /dev/null)
	
	check_bin_path "$BIN_PATH"
	bin_return=$?

	check_dir_path "$SOURCE_PATH"
	src_return=$?
	
	check_dir_path "$LIB_PATH"
	lib_return=$?

	# Display results
	
	# Display Structure results
	if [ -d "$STRUCTURE_PATH" ]
	then
		echo "[OK] ROOT: '$STRUCTURE_PATH'"
	else
		echo "[ERROR] '$STRUCTURE_PATH' is not a valid root directory for a java project."
		return 1
	fi

	# Display Source results
	if [ "$src_return" -ne 0 ]
	then
		echo "[ERROR] SOURCE: '$SOURCE_PATH'"
		if [ "$src_return" -eq 1 ]; then echo "--> source folder does not exist."; fi
		return 1
	else
		echo "[OK] SOURCE: '$SOURCE_PATH'"
	fi

	# Display Library directory results
	if [ "$lib_return" -ne 0 ]
	then
		echo "[WARN] LIBRARIES: '$LIB_PATH'"
		if [ "$lib_return" -eq 1 ]; then echo "--> library folder does not exist."; fi
		return 1
	else
		echo "[OK] LIBRARIES: '$LIB_PATH'"
	fi
	
	# Display Classpath results
	if [ "$bin_return" -ne 0 ]
	then
		echo "[ERROR] CLASSPATH: '$CLASSPATH'"
		if [ "$bin_return" -eq 1 ]; then echo "--> CLASSPATH is not set."; fi
		if [ "$bin_return" -eq 2 ]; then echo "--> CLASSPATH is not a directory."; fi
		if [ "$bin_return" -eq 3 ]; then echo "--> CLASSPATH is not named 'bin' conventionally."; fi
		return 1
	else
		echo "[OK] CLASSPATH: '$CLASSPATH'"
	fi
}

# Start the program
main $@

# Check if the program ran successfully
if [ $? -eq 0 ]
then 
	echo "All good to go!"
else
	echo "Errors occurred. See details above."
fi




